### ISSUE TITLE
Doesn't work on 67.2

### ISSUE THREAD

**Issue by ivancucer** [longzheng/sketch-randomSize#4]
Hey @longzheng 

Is there a chance this plugin is still alive? It'd be amazing if you have time to fix it ❤️

Thanks in advance!

Ivan

**Comment by longzheng** [comment]
I'm no longer using Sketch full-time so I didn't notice, but I've fixed the incompatibility with Sketch 67 and released an update. https://github.com/longzheng/sketch-randomSize/releases/download/3.0/RandomSize.sketchplugin.zip

**Comment by ivancucer** [comment]
Thanks for the update. You mean you created the same plugin but for Figma?

**Comment by longzheng** [comment]
I've switched to Figma but haven't made a similar plugin, I've not yet had the need for it.

**Comment by longzheng** [comment]
I've just created a version for Figma and submitted for review, will let you know if it's approved.

**Comment by longzheng** [comment]
Figma plugin approved https://www.figma.com/community/plugin/871561492051264078/random-size
